name = "medal"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-10-25"
kv_namespaces = [
  { binding = "KEYS", id = "PROD_ID", preview_id = "PREVIEW_ID" },
]